# Generated by Django 4.2.7 on 2023-11-14 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("test_task_app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="employee",
            old_name="second_name",
            new_name="last_name",
        ),
    ]
